language: R
r:
  - release
cache: packages

r_packages:
  - covr

r_github_packages: r-lib/pkgdown

before_install:
  - tlmgr install standalone

after_success:
  - Rscript -e 'library(covr); codecov()'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::build_favicons(pkg = ".", overwrite = FALSE); pkgdown::deploy_site_github()'
  skip_cleanup: true
